spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:mysql://localhost:3306/movieflix
    username: root
    password: fee3flaros
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  flyway:
    enabled: true


moviefix:
  security:
    secret: "palavra-secreta"